export default {
  RED_PRIMARY: 'rgba(153, 0, 0, 1)',
  YELLOW_PRIMARY: 'rgba(255, 204, 0, 1)',
  FONT_SIZE_SMALL: 12,
  CONTAINER_WIDTH_LARGE: '80%',
  CONTAINER_WIDTH_MEDIUM: '70%',
  FONT_SIZE_MEDIUM: 17,
  FONT_SIZE_LARGE: 20,
  
  
  
  FONT_WEIGHT_LIGHT: '200',
  FONT_WEIGHT_MEDIUM: '500',
  FONT_WEIGHT_BOLD: '700',
  BACKGROUND_COLOR_LIGHT: '#f0f6f7',
  CONTAINER_PADDING: 20,
};
